#!/bin/sh
set -e

# Autogenerated by update_socks5tun.sh — do not edit manually.
PREFIX6="64"
WAN_IF="eth0"

echo "[nat6_setup] prefix6=$PREFIX6 wan_if=$WAN_IF"

# 1) IPv6 forwarding: сейчас и персистентно
sysctl -w net.ipv6.conf.all.forwarding=1 >/dev/null || true
if [ -d /etc/sysctl.d ]; then
  echo 'net.ipv6.conf.all.forwarding=1' >/etc/sysctl.d/99-socks5tun-ipv6.conf || true
fi

# 2) nftables или ip6tables (в зависимости от системы)
if command -v nft >/dev/null 2>&1 && nft list tables 2>/dev/null | grep -q ' ip6 nat'; then
  nft list chain ip6 nat POSTROUTING 2>/dev/null | grep -q "ip6 saddr $PREFIX6 oif $WAN_IF masquerade"     || nft add rule ip6 nat POSTROUTING ip6 saddr $PREFIX6 oif $WAN_IF masquerade
  echo "[nat6_setup] nftables rule ensured"
else
  ip6tables -t nat -C POSTROUTING -s "$PREFIX6" -o "$WAN_IF" -j MASQUERADE 2>/dev/null     || ip6tables -t nat -A POSTROUTING -s "$PREFIX6" -o "$WAN_IF" -j MASQUERADE
  if command -v ip6tables-save >/dev/null 2>&1 && [ -d /etc/iptables ]; then
    ip6tables-save > /etc/iptables/rules.v6 || true
  fi
  echo "[nat6_setup] ip6tables rule ensured"
fi

exit 0
