#!/bin/sh
set -eu

# Autogenerated/managed by socks5tun updater.
PREFIX6="${PREFIX6:-fd00:0:0:8::/64}"
WAN_IF="${WAN_IF:-eth0}"

echo "[nat6_setup] prefix6=$PREFIX6 wan_if=$WAN_IF"

# 1) IPv6 forwarding (и персистентно)
sysctl -w net.ipv6.conf.all.forwarding=1 >/dev/null || true
if [ -d /etc/sysctl.d ]; then
  printf 'net.ipv6.conf.all.forwarding=1\n' >/etc/sysctl.d/99-socks5tun-ipv6.conf || true
fi

# 2) nftables only (не смешиваем с ip6tables-nft)
if command -v nft >/dev/null 2>&1; then
  # гарантируем, что таблица/цепочка есть
  nft list table ip6 nat >/dev/null 2>&1 || nft add table ip6 nat
  nft list chain ip6 nat POSTROUTING >/dev/null 2>&1 || \
    nft add chain ip6 nat POSTROUTING '{ type nat hook postrouting priority srcnat; policy accept; }'

  # Дедупликация: удаляем ВСЕ старые masquerade для нашего префикса (любые варианты oif/oifname, с/без counter)
  for h in $(nft -a list chain ip6 nat POSTROUTING 2>/dev/null \
             | awk -v p="$PREFIX6" '$0 ~ "ip6 saddr " p && $0 ~ /masquerade/ {print $NF}'); do
    nft delete rule ip6 nat POSTROUTING handle "$h" 2>/dev/null || true
  done

  # Кладём одно каноничное правило
  nft add rule ip6 nat POSTROUTING ip6 saddr $PREFIX6 oifname "$WAN_IF" counter masquerade

  echo "[nat6_setup] nftables rule ensured (deduped)"
else
  echo "[nat6_setup] nft not found; skipping NAT66"
fi

exit 0
