- name: Install dependencies (without self)
  shell: bash
  run: |
    set -euxo pipefail
    python -m pip install --upgrade pip

    # 1) убрать уже установленный/закешированный socks5tun
    pip uninstall -y socks5tun || true

    # 2) НЕ устанавливать себя из requirements.txt
    if [ -f requirements.txt ]; then
      # вырезаем любые строки с socks5tun (с версией или без)
      grep -viE '^\s*socks5tun(\s|==|>=|$)' requirements.txt > req_noself.txt || true
      if [ -s req_noself.txt ]; then
        pip install -r req_noself.txt
      fi
    fi

    # 3) поставить проект из исходников
    pip install -e .

    # 4) показать, откуда импортируется пакет (диагностика)
    python - <<'PY'
import socks5tun, inspect, sys
print("PATH:", socks5tun.__file__)
print("PYTHON:", sys.version)
print("VERSION:", getattr(socks5tun, "__version__", "n/a"))
PY

- name: Run tests
  run: pytest -q
